### ISSUE TITLE
Collectionname change on production

### ISSUE THREAD

**Issue by snowVolleyball** [iyobo/pouchorm#5]
If I start to create a collection with a name „building“ I can see that a similar collection is created in the database. This is what I assumed and it’s working in the development environment very nice as expected.

I’m sync my local pouchDb with a server couchDb.

But as soon I compile my paw app ( build with angular 9) as production I have the problem that the collection name become something different like „ab“. The application is still working but let‘s say I have an second application that like to work with the data have now trouble to find data as they would assume to see the original „building“ name and as this application is also compiled in prod they know have another name „cd“ for the same collection. So in fact they can’t access each other’s informations. 

I have no evidence but I assume that may the compiler for prod is doing a kind of obfuscating for the production.

Would be great if you have any idea how I can avoid this behavior
Best regards

**Comment by aaronhuggins** [comment]
Do you have a code example?

**Comment by snowVolleyball** [comment]
Do you have any idea where I have to search for the options? As I did not change anyhing in the angular.json or tsconfig.json I have no idea where I have to search for the optimization. I fare as I understand there is no option in typescript foreseen for this. But may I'm mistaken

**Comment by aaronhuggins** [comment]
From https://angular.io/guide/workspace-config
> The production configuration sets defaults that optimize the app in a number of ways, such as bundling files, minimizing excess whitespace, removing comments and dead code, and rewriting code to use short, cryptic names ("minification").

The reason I asked to see config and code examples is that there's a number of ways to go about fixing your issue, all of which are related to typescript or angular and not really specific to PouchDB or PouchORM.

1. One possible solution without reconfiguring: https://stackoverflow.com/questions/48837317/how-can-i-keep-a-specific-variable-name-after-javascript-minification-performed#48837802
2. Possibly set angular production optimization to false for scripts
3. Change your cli parameters https://angular.io/cli/build
4. Angular uses webpack under the hood, so it's probably a good idea to look at the relationship between angular and webpack to see if you can leverage more specific minification options for your use case. https://stackoverflow.com/questions/51068908/angular-cli-custom-webpack-config#51130803
5. You may also want to explore separating your collection and model classes into a completely independent TypeScript/JavaScript project that you then import into your Angular project.

**Comment by snowVolleyball** [comment]
wow, I guess I need know some time to check all this :-)
Point 2 I already tried without success.

The differences are as follow
{
 "_id": "5251e652-589b-5b82-8cd1-0b27cfd35d93",
 "_rev": "1-2b7e7cd3fff5225697ffaf8581c472f0",
 "name": "Angular run with build --prod",
 "sam": "user1",
 "profession": "teacher",
 "$timestamp": 1587905147462,
 "$collectionType": "TeacherCollection"
}
id"8c8a47e5-4936-5e10-88b4-cc62e7d5d62a"
{
 "_id": "8c8a47e5-4936-5e10-88b4-cc62e7d5d62a",
 "_rev": "1-7ba0100da2ae36c049e2450013e1db19",
 "name": "Angular debug",
 "sam": "user2",
 "profession": "Fachbereichsleiter IT-Berufsbildung",
 "$timestamp": 1587904786121,
 "$collectionType": "bD"
}

**Comment by snowVolleyball** [comment]
point 2 was the key. I had change in the angular.json file the optimization= option to false.
This solved the problem for me. Thank you so much for this very quick answer.
