### ISSUE TITLE
What is the reasoning behind using chance.guid for the doc ids?

### ISSUE THREAD

**Issue by AKRFranko** [iyobo/pouchorm#7]
Great simple and useful lib you got here, got me started really quick with getting my head around some data modeling for a new project. With all these new fangled NoSQL/GraphQL complexotrons it's refreshing to find something simple, easy an concise. 

I'm curious as to what your reasoning is behind using chance.guid for the doc ids?
Do you plan for a way to have it be provided by the user of the library if I want to roll my own?
 

P.S: I thought I myself could label this issue as "question" but apparently not.

**Comment by iyobo** [comment]
Hey @AKRFranko,

Sorry for the late response.
You can totally provide your own ids by defining the `_id` field with your unique ID when running `upsert(...)` in your collection.

```
userCollection.upsert({
   _id: "GENERATE_YOUR_OWN"
  name: "Tony Montana"
});
```

**Comment by iyobo** [comment]
But this question does spark an epiphany.
Perhaps it makes sense to add a a property to collections which is a settable function users can define to automatically generate their IDs in the way they want.

This way, each collection can be made to generate their own formats of IDs, kind of like Stripe if you're familiar with that.
So Something like ...

```
userCollection.idGenerator = ()=>`user_${someIdGenerator()}`

const newUser = userCollection.upsert({
  name: "Tony Montana"
});

//newUser._id === 'user_cnvvvifjkemnkkjd'
```

**Comment by iyobo** [comment]
@AKRFranko PouchORM v1.3.0 now no longer uses the `chance` library for default uuid generation, but uses `uuid`.

Also please see docs @ https://github.com/iyobo/pouchorm#custom-id-generation 
for how to define custom id generation per collection.
